apiVersion: keda.sh/v1alpha1
kind: KedaController
metadata:
  annotations:
  finalizers:
    - finalizer.kedacontroller.keda.sh
  labels:
    app.kubernetes.io/instance: keda
  name: keda
  namespace: testapp
spec:
  admissionWebhooks:
    logEncoder: console
    logLevel: info
  metricsServer:
    logLevel: '0'
  operator:
    logEncoder: console
    logLevel: error
  watchNamespace: ''
