apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-custom-metrics-autoscaler-operator.openshift-keda: ""
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: openshift-custom-metrics-autoscaler-operator
  namespace: testapp
spec:
  channel: stable
  installPlanApproval: Manual
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: custom-metrics-autoscaler.v2.11.2-311
